= Node.js API Compatability
Lance Ball <lball@redhat.com>
2013-04-15
:awestruct-layout: base

== Nodyn Completion of the Node.js API ==

The Node.js API is fairly large, and some of it is really very specific to
the fact that Node.js is built in C and thus dependent on system level 
functionality. The system level addons are an obvious example of this. Since
Nodyn is written in Java and thus freed from the binary shackles of the
Operating System, some of the stuff in Node.js just doesn't make sense
in Nodyn.

This document is an attempt to clarify what bits of the Node.js API are
available in Nodyn and to identify any workarounds as necessary.

In some cases, we've copied the Node.js javascript files as-is. When the Node.js
source is dependent only on Javascript bits, and nothing in the C bindings,
there's no need to rewrite it all. In other cases, where Node.js depends on
C bindings, we've got our own spin on things with the vert.x engine or even
just plain old Java code.

Work on the API implementation is prioritized by the current Node.js Stability
Index.  Features with a stability index of 2 or below are less important in
most cases than the more stable features.

[role=api]
=== Assert ===
- Node.js reference http://nodejs.org/api/assert.html

Complete. All functions should behave as expected.  A direct copy of Node.js
source code.

[role=api]
=== Buffer ===
- Node.js reference http://nodejs.org/api/buffer.html
- Nodyn status details: link:/api/buffer[Buffer Status]

In progress (lanceball).

[role=api]
=== C Addons ===
- Node.js reference http://nodejs.org/api/addons.html

Not applicable. Extensions to Nodyn can be written in Java, Javascript, JRuby,
Python or any other language supported by vert.x.

[role=api]
=== Child Processes ===
- Node.js reference http://nodejs.org/api/child_processes.html

Not applicable. If we do implement this API, it certainly won't actually be
spawning new processes.

[role=api]
=== Cluster ===
- Node.js reference http://nodejs.org/api/cluster.html

Clustering is handled for now through vert.x builtin clustering, which itself
uses link:http://www.hazelcast.com/[hazelcast] for the implementation. Vert.x
does not yet expose clustering data or an API.

[role=api]
=== Crypto ===
- Node.js reference http://nodejs.org/api/crypto.html

In progress (abstractj).

[role=api]
=== Debugger ===
- Node.js reference http://nodejs.org/api/debugger.html

Work not started.

[role=api]
=== DNS ===
- Node.js reference http://nodejs.org/api/dns.html

Work not started.

[role=api]
=== Domain ===
- Node.js reference http://nodejs.org/api/domain.html

Incomplete. (Node.js stability index 1)

[role=api]
=== Events ===
- Node.js reference http://nodejs.org/api/events.html

Complete. All functions should behave as expected.  A direct copy of Node.js
source code.

[role=api]
=== File System ===
- Node.js reference http://nodejs.org/api/fs.html

In progress (sblanc, et al).

[role=api]
=== Globals ===
- Node.js reference http://nodejs.org/api/globals.html

Mostly complete. The CommonJS module loader built into DynJS is lacking a few
features. The following functions and objects are not yet supported.

  - `require.resolve()`
  - `require.caches`
  - `require.extensions`

Also, since many vert.x apps run from a Jar file, I'm not quite sure what to do
yet with `__filename` and `__dirname`.

[role=api]
=== HTTP ===
- Node.js reference http://nodejs.org/api/http.html
- Nodyn status details: link:/api/http[HTTP Status]

Complete, except for http.Agent and other issues noted in the compatibility doc.

[role=api]
=== HTTPS ===
- Node.js reference http://nodejs.org/api/https.html

Work not started.

[role=api]
=== Modules ===
- Node.js reference http://nodejs.org/api/modules.html

Complete.

[role=api]
=== Net ===
- Node.js reference http://nodejs.org/api/net.html
- Nodyn status details: link:/api/net[Net Status]

Partially complete. See the compatibility doc for details.

[role=api]
=== OS ===
- Node.js reference http://nodejs.org/api/os.html
- Nodyn status details: link:/api/os[OS Status]

Incomplete. Some functions are currently stubbed.

[role=api]
=== Path ===
- Node.js reference http://nodejs.org/api/path.html

Complete. All functions should behave as expected.

[role=api]
=== Process ===
- Node.js reference http://nodejs.org/api/process.html

Incomplete (lanceball)

[role=api]
=== Punycode ===
- Node.js reference http://nodejs.org/api/punycode.html

Complete. All functions should behave as expected.

[role=api]
=== Query Strings ===
- Node.js reference http://nodejs.org/api/querystring.html

Complete. All functions should behave as expected.

[role=api]
=== Readline ===
- Node.js reference http://nodejs.org/api/readline.html

Work not started.

[role=api]
=== REPL ===
- Node.js reference http://nodejs.org/api/repl.html

Work not started.

[role=api]
=== STDIO ===
- Node.js reference http://nodejs.org/api/stdio.html

Complete. All functions should behave as expected.

[role=api]
=== Stream ===
- Node.js reference http://nodejs.org/api/stream.html

Complete. All functions should behave as expected.

[role=api]
=== String Decoder ===
- Node.js reference http://nodejs.org/api/string_decoder.html

Work not started.

[role=api]
=== Timers ===
- Node.js reference http://nodejs.org/api/timers.html

Complete. All functions should behave as expected.

[role=api]
=== TLS/SSL ===
- Node.js reference http://nodejs.org/api/tls.html

Work not started.

[role=api]
=== TTY ===
- Node.js reference http://nodejs.org/api/tty.html

Work not started.

[role=api]
=== UDP/Datagram ===
- Node.js reference http://nodejs.org/api/dgram.html

Complete http://github.com/projectodd/nodyn/issues/30

[role=api]
=== URL ===
- Node.js reference http://nodejs.org/api/url.html

Complete. All functions should behave as expected.

[role=api]
=== Utilities ===
- Node.js reference http://nodejs.org/api/util.html

Complete. All functions should behave as expected. Modified copy of Node.js
source code.

[role=api]
=== VM ===
- Node.js reference http://nodejs.org/api/vm.html

Work not started.

[role=api]
=== ZLIB ===
http://nodejs.org/api/vm.html

Work not started, but probably irrelevant given the platform differences.

