source 'https://rubygems.org'

gem 'awestruct', '~>0.5.0' 
gem 'asciidoctor', '~>0.1.1'
gem 'haml', '~>4.0.2'
gem 'rake', '~>10.0.4'
gem 'coffee-script', '~>2.2.0'
gem 'htmlcompressor', '~>0.0.6'
gem 'uglifier', '~>2.0.1'
gem 'rb-fsevent', '~>0.9.3'
